apiVersion: v1
data:
  CONCH_ENDPOINT: http://conch-model:54001
  MEDSAM_ENDPOINT: http://medsam-model:54003
  MINIO_ACCESS_KEY: biotune
  MINIO_ENDPOINT: minio-endpoint:9000
  # INSERT CORRECT PASSWORD
  MINIO_SECRET_KEY: <insert correct password>
  VIRCHOW_ENDPOINT: http://virchow-model:54002
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: biotune-ai-env-kube
  name: env-kube
